name: Setup Node environment
description: Prepare the workspace for a Node project.
inputs:
  node-version:
    description: The Node.js version to install
    required: false
    default: '16.x'
  pnpm-version:
    description: pnpm version to install
    required: false
    default: '7'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 7
    - name: Get pnpm store directory
      id: pnpm-cache
      run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      shell: bash
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        CYPRESS_INSTALL_BINARY: '0'
    - name: Add pnpm binaries to path
      shell: bash
      run: |
        echo "$(pnpm bin)" >> $GITHUB_PATH
        echo "$(pnpm -g bin)" >> $GITHUB_PATH